name: Black Code Formatter

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: jpetrucciani/black-check@19.10b0
      - uses: py-actions/flake8@v1.0.1
        with:
          max-line-length: 120
